#%RAML 1.0 Trait
headers:
  client_id:
    description: The Client-ID of the Application. Will be provided by the Portal
    type: string
    example: c6VwL5qIGQAhJfmZADoR
  client_secret:
    description: The Client-Secret of Application. Will be provided by the Portal.
    type: string
    example: dGfk4xKTGPcZ4MvMxpl5
