#%RAML 1.0 NamedExample
sample-api-response-200:
  id: "0012000001ZbRgPAAX"
  name: "Jason Bourne"
  phone: "1-(318)596-8473"
  email: "test@example.com"
  createdDate: "2016-03-24T15:00:00.000Z"
  lastModifiedDate : "2016-03-24T15:00:00.000Z"
  lastModifiedById : "123456"