#%RAML 1.0 DocumentationItem
title: Standard API Template
content: |
    This is a generic API Template meant to be reused as a baselines for Designing API specifications using Design Center in Anypoint Platform. 

    It forms the base for an accelerated delivery of API spec by removing all common concerns mentioned above. API Designer just needs to focus on -
    - API Resource hierarchy
    - Examples of Requests and Responses
    - DataTypes for the Requests and Responses
